### ISSUE TITLE
This project appears to introduce ~1267 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-preprocessor-registry#15]
## own files that may be a mistake:
- [x] tests
## dependencies that may need to be investigated:
- [ ] broccoli-clean-css     811 [PR](https://github.com/shinnn/broccoli-clean-css/pull/17)
- [x] lodash     434 may only need a subset of lodash, via one of the subset packages

**Comment by locks** [comment]
`broccoli-clean-css` has a [properly configures `package.json.files`](https://github.com/shinnn/broccoli-clean-css/blob/master/package.json#L5-L7). It needs its dependencies checked, I'm guessing?

**Comment by stefanpenner** [comment]
@locks most likely

**Comment by Turbo87** [comment]
@locks did you check the deps on `broccoli-clean-css`?

**Comment by locks** [comment]
@Turbo87 I don't remember anymore, we should do another pass!

**Comment by locks** [comment]
@Turbo87 just checked, seems like `broccoli-clean-css` needs its dependencies updated as they seem to have `files` configured, then a release, then we need to update our dependency on it.

**Comment by Turbo87** [comment]
@locks okay, thanks. could you open a PR updating the dependencies on `broccoli-clean-css`?

**Comment by locks** [comment]
@Turbo87 https://github.com/shinnn/broccoli-clean-css/pull/17
