### ISSUE TITLE
Missing package.json dependency on broccoli-clean-css - breaks with npm@3

### ISSUE THREAD

**Issue by tylergibson** [ember-cli/ember-cli-preprocessor-registry#2]
In updating to npm3, due to the flattening of package dependencies, "ember build -prod" breaks because ember-cli-preprocessor-registry can't load the broccoli-clean-css module.

This doesn't occur with npm@2.x because in walking up the folder heirarchy, ember-cli installs broccoli-clean-css as a bundled dependency.  But with npm@3, it is not in a parent, but rather a sibling's child folder.

Since ember-cli-preprocessor-registry has a dependency on broccoli-clean-css, it should include it as a dependency in package.json.

This also fixes ember-cli so it works properly with npm@3.x

**Comment by stefanpenner** [comment]
The problem is real but the solution isn't correct. It needs to resolve those deps relative the project, not this local package

**Comment by stefanpenner** [comment]
Good catch

**Comment by felixrieseberg** [comment]
I'm slowly turning my whole team into Ember evangelists :dancers:

**Comment by stefanpenner** [comment]
@felixrieseberg :+1:
