### ISSUE TITLE
New package release after exists-sync change

### ISSUE THREAD

**Issue by chauhansudhir** [ember-cli/ember-cli-preprocessor-registry#25]
@rwjblue ember-cli-preprocess-registry@3.1.1 still has exists-sync(deprecated) dependency. Will you be able to publish a new release. I see master does't have dependency to exists-sync.
Thanks
Sudhir

**Comment by poplevente** [comment]
agree, if someone can do it, would be great

**Comment by stefanpenner** [comment]
@rwjblue looks like you release 4.0.0-beta.1, should we cut 4.0.0 stable?

**Comment by stefanpenner** [comment]
I'll back-port the exists-sync change to 3.1.x in the meantime.

**Comment by stefanpenner** [comment]
released as v3.1.2 🎉
