### ISSUE TITLE
broccoli-clean-css severely outdated 

### ISSUE THREAD

**Issue by XrXr** [ember-cli/ember-cli-preprocessor-registry#4]
`0.2.0`, the current version used is over a year old. The newest version is 1.1.0

We need to disable zero unit trimming to support IE11, but we can't with the current version of `clean-css`

It would be nice if we can specify the version of `clean-css`  we want to use

@stefanpenner

**Comment by stefanpenner** [comment]
Or we should bump this repo to use the latest. Would accept a pr

**Comment by XrXr** [comment]
@stefanpenner pr ready #5
