### ISSUE TITLE
broken @import errors with the ember-cli-jquery-ui addon

### ISSUE THREAD

**Issue by eibrahim** [ember-cli/ember-cli-preprocessor-registry#8]
I am getting the broken @import errors with the ember-cli-jquery-ui addon after upgrading to ember 2.3.0.  The only way I was able to make my build work was to add `ember-cli-build.js`

```
    minifyCSS: {
      enabled: false,
    },
```

But obviously this turns off my CSS minification...  Any idea what is going on?

The full error is:

```
File: assets/vendor.css
Broken @import declaration of "theme.css"
Broken @import declaration of "accordion.css"
Broken @import declaration of "autocomplete.css"
Broken @import declaration of "button.css"
Broken @import declaration of "datepicker.css"
Broken @import declaration of "dialog.css"
Broken @import declaration of "draggable.css"
Broken @import declaration of "menu.css"
Broken @import declaration of "progressbar.css"
Broken @import declaration of "resizable.css"
Broken @import declaration of "selectable.css"
Broken @import declaration of "selectmenu.css"
Broken @import declaration of "sortable.css"
Broken @import declaration of "slider.css"
Broken @import declaration of "spinner.css"
Broken @import declaration of "tabs.css"
Broken @import declaration of "tooltip.css"
Error: Broken @import declaration of "theme.css"
Broken @import declaration of "accordion.css"
Broken @import declaration of "autocomplete.css"
Broken @import declaration of "button.css"
Broken @import declaration of "datepicker.css"
Broken @import declaration of "dialog.css"
Broken @import declaration of "draggable.css"
Broken @import declaration of "menu.css"
Broken @import declaration of "progressbar.css"
Broken @import declaration of "resizable.css"
Broken @import declaration of "selectable.css"
Broken @import declaration of "selectmenu.css"
Broken @import declaration of "sortable.css"
Broken @import declaration of "slider.css"
Broken @import declaration of "spinner.css"
Broken @import declaration of "tabs.css"
Broken @import declaration of "tooltip.css"
    at arrayToError (/myapp/node_modules/array-to-error/index.js:41:15)
    at minifyCallback (/myapp/node_modules/clean-css-promise/index.js:33:20)
    at whenSourceMapReady (/myapp/node_modules/clean-css/lib/clean.js:139:16)
    at Object.whenDone (/myapp/node_modules/clean-css/lib/clean.js:155:14)
    at processNext (/myapp/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/myapp/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at processNext (/myapp/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at inlineLocalResource (/myapp/node_modules/clean-css/lib/imports/inliner.js:347:12)
    at inline (/myapp/node_modules/clean-css/lib/imports/inliner.js:218:10)
    at importFrom (/myapp/node_modules/clean-css/lib/imports/inliner.js:74:12)
```

by the way `ember build` works but `ember build --environment production` breaks which I guess comes back to minifyCSS.enabled = true 
#6

**Comment by stefanpenner** [comment]
does this happen with a basic app, or does it require something special? Can you provide a reduced application that demonstrate this, as it will aide in debugging.

**Comment by eibrahim** [comment]
very easy to reproduce...

`ember new demo`
`ember install ember-cli-jquery-ui`
`ember build --environment production`

**Comment by stefanpenner** [comment]
@eibrahim thank you

**Comment by jasonmit** [comment]
I'm seeing this as well, looks like it's related to clean-css

**Comment by jasonmit** [comment]
Rolling back broccoli-clean-css to 1.0.0 resolves the issue.  I'll spend some more time seeing what happened, but it looks like the options hash being passed into clean-css-promise doesn't seem right, lots of options unrelated to clean-css are being passed in.

**Comment by eibrahim** [comment]
So can I keep 1.1 and set relativeTo = assets

**Comment by jasonmit** [comment]
No, that won't work.

**Comment by jasonmit** [comment]
So I think I got to the bottom of what is happening.  broccoli-clean-css was previously using clean-css and in 1.1.0 now uses clean-css-promise.  clean-css-promise throws when anything is pushed to `context.errors` where before it would swallow.

https://github.com/jakubpawlowicz/clean-css/blob/master/lib/imports/inliner.js#L345-L348

This code path is hit in both broccoli-clean-css 1.0.0 and 1.1.0 but now results in the promise being rejected where it should just ignore.  Or, alternatively there shouldn't be imports by the time clean css tries to minify the code.  IE, postcss, or whatever preprocessor, is being used should have processed them out before clean css reads the files.

**Comment by jasonmit** [comment]
```js
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    minifyCSS: {
      processImport: false
    }
  });
}
```

The problem should now go away...

**Comment by jasonmit** [comment]
```js
var app = new EmberApp(defaults, {
    minifyCSS: {
      options: {
        processImport: false
      }
    }
});
```
Should solve/workaround this...

**Comment by eibrahim** [comment]
The processImport workaround worked for me and I was able to build with the production flag.  But wouldn't that break the CSS?  If a css import abc.css and we tell it not to process it, does that mean abc.css will not be part of the final css?

**Comment by jasonmit** [comment]
@eibrahim clean-css is used for minifying.  You likely are using a preprocessor like LESS or SaSS to handle imports.

**Comment by jaaksarv** [comment]
I'm having the same problem. Any solutions?

**Comment by RogerLevy** [comment]
We're having the same problem.

**Comment by Kurshith** [comment]
Having same problem. Any updates?

**Comment by rwjblue** [comment]
`processImport: false` was added by default in https://github.com/ember-cli/ember-cli/pull/5874, which should address this for folks.

Closing for now (let me know if that does not address folks' issue).
